### ISSUE TITLE
Cannot build on 10.6.8 with Xcode 4.2 - 2 errors

### ISSUE THREAD

**Issue by Clouds123** [kstenerud/ObjectAL-for-iPhone#53]
Both errors in OALAudioSession.m:: handleInterruption: method:

1) Sematic Issue: Use of undeclared identifier 'AVAudioSessionInterruptionTypeBegan on line 642

2) Sematic Issue: Use of undeclared identifier 'AVAudioSessionInterruptionTypeEnded on line 645

These errors occur even when building with iOS 6 SDK.
