### ISSUE TITLE
objc_msgSend Error

### ISSUE THREAD

**Issue by RhysLindmark** [kstenerud/ObjectAL-for-iPhone#78]
In `OALSuspendHandler.m,`
in `- (void) setManuallySuspended:(bool) value,`
there's an error on this line (156):

`objc_msgSend(suspendStatusChangeTarget, suspendStatusChangeSelector, manualSuspendLock);`

The error is `"Too many arguments to function call, expected 0, have 3."`

It looks as if this StackOverflow post is helpful: http://stackoverflow.com/questions/24922913/too-many-arguments-to-function-call-expected-0-have-3

Even though I have changed my 'Enable strict checking of objc_msgSend Calls' to NO, I cannot run the project.

Finally, this error showed up for me when I updated from Cocoapods 0.35.0 to 0.36.0.beta.2.

Thanks and let me know if you have any questions!

**Comment by RhysLindmark** [comment]
Other quick question -- Should I also post this to the Cocoapods issue repo?

**Comment by michalciolek** [comment]
You must force update lib e.g.:
```pod 'ObjectAL-for-iPhone', :git => 'https://github.com/kstenerud/ObjectAL-for-iPhone.git'```
In commit a2252f3b48610012a8697b55b18be987c83b4bf2 that was fixed but @kstenerud don't update version code. You have 2.4 version, see: https://github.com/kstenerud/ObjectAL-for-iPhone/blob/2.4/ObjectAL/ObjectAL/Session/OALSuspendHandler.m#L156

**Comment by oriolblanc** [comment]
@michalciolek could you create a new release with this fix?

**Comment by kstenerud** [comment]
Whoops. Forgot to tag it :P
Tagged 2.5 now, with updated podspec.

**Comment by kstenerud** [comment]
OK, should be properly tagged now.

**Comment by Shiver02** [comment]
Hi, @kstenerud, I was wondering if you could push the podspec for 2.5 on cocoapods.org as well :)

**Comment by Sajjon** [comment]
If anyone is experiencing problems with any Cocoapods project due to the objc_msgsend has too many arguments issue, I have fixed it using the post_installer script below.

What I am doing is that I am iterating through all targets in the Pods.xcproj and setting the flag 'ENABLE_STRICT_OBJC_MSGSEND' to NO.

```ruby
post_install do |installer|
	installer.project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "NO"
		end
	end
end
```

**Comment by vanderneut** [comment]
I see you updated your podspec to point to 2.5, yet when I do a pod install it sees 2.4 as the latest version... Does michalciolek's Feb 5 comment to force a lib update fix that?

**Comment by vanderneut** [comment]
RhysLindmark,

Can you please submit your 2.5 updated podspec to cocoapods.org? 

>: pod search ObjectAL-for-iPhone

-> ObjectAL-for-iPhone (2.4)
   Mac and iOS Audio, minus the headache.
   pod 'ObjectAL-for-iPhone', '~> 2.4'
   - Homepage: http://kstenerud.github.io/ObjectAL-for-iPhone/
   - Source:   https://github.com/kstenerud/ObjectAL-for-iPhone.git
   - Versions: 2.4, 2.3, 2.2, 2.1 [master repo]

Thanks,
Erik

**Comment by dsmitchell** [comment]
I'm having the same problems @vanderneut is having. cocoapods.org still points to version 2.4.

**Comment by kstenerud** [comment]
Should be updated now.

**Comment by dsmitchell** [comment]
Thank you! I noticed :)

David

**Comment by vanderneut** [comment]
Thanks so much! Cocoapods is now pulling in version 2.5 indeed :-) Very much appreciated! 

Erik

**Comment by RhysLindmark** [comment]
I can mark this issue as resolved, then?

**Comment by vanderneut** [comment]
Yes, you can - thanks RhysLindmark :-)
